<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\ServiceItem;
use App\Models\ServiceItemImage;
use Illuminate\Database\Seeder;

class ServiceItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // ==========================================
            // 1. Two-Wheelers (two_wheelers)
            // ==========================================
            [
                'service_type' => 'two_wheelers',
                'name' => 'Honda Activa 6G (110cc)',
                'category' => 'Scooter (110cc-125cc)',
                'description' => 'Lightweight, effortless automatic scooter perfect for local Honnavar town, Eco Beach, and mangrove trails. 50+ kmpl mileage with sanitized helmets included.',
                'price_base' => 350.00,
                'price_unit' => 'per_day',
                'capacity' => '2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Zero Deposit',
                'features' => ['2 ISI Helmets Included', 'Phone Mount & USB Charger', 'Tubeless Tyres', 'Well Serviced & Polished', 'Unlimited KM Option'],
                'status' => 'available',
                'sort_order' => 1,
            ],
            [
                'service_type' => 'two_wheelers',
                'name' => 'TVS Jupiter 125 Disc',
                'category' => 'Scooter (110cc-125cc)',
                'description' => 'Comfortable 125cc scooter with massive under-seat storage, external fuel filler, and metal body. Smooth ride across Honnavar coastal routes.',
                'price_base' => 400.00,
                'price_unit' => 'per_day',
                'capacity' => '2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Huge Storage',
                'features' => ['2 ISI Helmets Included', 'Phone Mount & USB Charger', 'Well Serviced & Polished', 'Complimentary City Map'],
                'status' => 'available',
                'sort_order' => 2,
            ],
            [
                'service_type' => 'two_wheelers',
                'name' => 'Suzuki Access 125 Bluetooth Edition',
                'category' => 'Scooter (110cc-125cc)',
                'description' => 'Peppy Japanese engine with retro styling and digital console with turn-by-turn navigation. Ideal for highway cruising to Murudeshwar.',
                'price_base' => 450.00,
                'price_unit' => 'per_day',
                'capacity' => '2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Turn Navigation',
                'features' => ['2 ISI Helmets Included', 'Phone Mount & USB Charger', 'Tubeless Tyres', 'Unlimited KM Option'],
                'status' => 'available',
                'sort_order' => 3,
            ],
            [
                'service_type' => 'two_wheelers',
                'name' => 'Yamaha FZ-S V3 (150cc)',
                'category' => 'Commuter Bike (150cc)',
                'description' => 'Sporty naked streetfighter with single-channel ABS, fat radial rear tyre, and relaxed upright riding posture for Ghats twisties.',
                'price_base' => 650.00,
                'price_unit' => 'per_day',
                'capacity' => '2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Sport Naked',
                'features' => ['2 ISI Helmets Included', 'Tubeless Tyres', 'Well Serviced & Polished', 'Phone Mount & USB Charger'],
                'status' => 'available',
                'sort_order' => 4,
            ],
            [
                'service_type' => 'two_wheelers',
                'name' => 'Royal Enfield Classic 350 Reborn',
                'category' => 'Cruiser (350cc)',
                'description' => 'Iconic thumper cruiser engineered for the NH66 coastal highway, Mirjan Fort, and Gokarna cliffside trails. High torque and comfortable touring.',
                'price_base' => 850.00,
                'price_unit' => 'per_day',
                'capacity' => '2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Highway Legend',
                'features' => ['2 ISI Helmets Included', 'Dual Disc ABS', 'Well Serviced & Polished', 'Unlimited KM Option'],
                'status' => 'available',
                'sort_order' => 5,
            ],
            [
                'service_type' => 'two_wheelers',
                'name' => 'Royal Enfield Himalayan 411',
                'category' => 'Adventure Touring',
                'description' => 'Purpose-built dual sport adventure tourer with 220mm ground clearance and long travel suspension. Built for Jog Falls and Yana rock trails.',
                'price_base' => 1200.00,
                'price_unit' => 'per_day',
                'capacity' => '2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&auto=format&fit=crop&q=80',
                'badge' => 'All-Terrain',
                'features' => ['2 ISI Helmets Included', 'Phone Mount & USB Charger', 'Pannier Stays Available', 'Unlimited KM Option'],
                'status' => 'available',
                'sort_order' => 6,
            ],
            [
                'service_type' => 'two_wheelers',
                'name' => 'Ather 450X Gen 3 Fast Charging',
                'category' => 'Electric Scooter',
                'description' => 'Next-gen electric scooter with Warp mode, touch dashboard, Google Maps integration, and 105km true range per charge.',
                'price_base' => 500.00,
                'price_unit' => 'per_day',
                'capacity' => '2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Green Mobility',
                'features' => ['Portable Charger Free', '2 ISI Helmets Included', 'Tubeless Tyres', 'Well Serviced & Polished'],
                'status' => 'available',
                'sort_order' => 7,
            ],

            // ==========================================
            // 2. Taxi & Cab Services (taxi)
            // ==========================================
            [
                'service_type' => 'taxi',
                'name' => 'Maruti Suzuki Dzire AC Sedan',
                'category' => 'Sedan (Dzire/Etios 4+1)',
                'description' => 'Comfortable, fuel-efficient 4-seater sedan for station pickups, couple getaways, and outstation trips across coastal Uttara Kannada.',
                'price_base' => 14.00,
                'price_unit' => 'per_km',
                'capacity' => '4+1 Passengers',
                'image_url' => 'https://images.unsplash.com/photo-1550355291-bbee04a92027?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Best Value',
                'features' => ['Chilled Dual AC', 'Commercial Yellow Board', 'Fastag Enabled', 'Clean & Sanitized Daily'],
                'status' => 'available',
                'sort_order' => 1,
            ],
            [
                'service_type' => 'taxi',
                'name' => 'Toyota Etios Platinum Diesel',
                'category' => 'Sedan (Dzire/Etios 4+1)',
                'description' => 'Renowned for class-leading rear legroom and huge 595-litre boot space. Reliable airport transfers to Goa (GOI/GOX) and Mangaluru (IXE).',
                'price_base' => 13.50,
                'price_unit' => 'per_km',
                'capacity' => '4+1 Passengers',
                'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Airport Ready',
                'features' => ['Chilled Dual AC', 'Experienced Hill & Ghat Driver', 'Luggage Carrier on Roof', 'Fastag Enabled'],
                'status' => 'available',
                'sort_order' => 2,
            ],
            [
                'service_type' => 'taxi',
                'name' => 'Maruti Suzuki Ertiga Smart Hybrid AC',
                'category' => 'SUV (Ertiga 6+1)',
                'description' => 'Spacious 6-seater family SUV with roof-mounted blower vents and modular folding rear seats. Perfect for temple and beach hopping.',
                'price_base' => 17.00,
                'price_unit' => 'per_km',
                'capacity' => '6+1 Passengers',
                'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Family Favorite',
                'features' => ['Chilled Dual AC', 'Commercial Yellow Board', 'Fastag Enabled', 'Bluetooth Music System', 'GPS Monitored'],
                'status' => 'available',
                'sort_order' => 3,
            ],
            [
                'service_type' => 'taxi',
                'name' => 'Toyota Innova Crysta Luxury Captain Seats',
                'category' => 'Premium MUV (Innova Crysta 7+1)',
                'description' => 'The gold standard in Indian highway travel. Whisper-quiet cabin, plush captain armchairs, and effortless cruising through Ghat curves.',
                'price_base' => 22.00,
                'price_unit' => 'per_km',
                'capacity' => '7+1 Passengers',
                'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Executive Comfort',
                'features' => ['Chilled Dual AC', 'Commercial Yellow Board', 'Experienced Hill & Ghat Driver', 'Bluetooth Music System', 'Clean & Sanitized Daily'],
                'status' => 'available',
                'sort_order' => 4,
            ],
            [
                'service_type' => 'taxi',
                'name' => 'Force Urbania Executive Luxury Coach',
                'category' => 'Tempo Traveller (12+1)',
                'description' => 'European-inspired panoramic windows, individual AC vents, ambient mood lighting, and reclining captain seats for extended group tours.',
                'price_base' => 28.00,
                'price_unit' => 'per_km',
                'capacity' => '12+1 Passengers',
                'image_url' => 'https://images.unsplash.com/photo-1464219789935-c2d9d9aba644?w=800&auto=format&fit=crop&q=80',
                'badge' => 'VIP Group Travel',
                'features' => ['Chilled Dual AC', 'Commercial Yellow Board', 'Luggage Carrier on Roof', 'GPS Monitored', 'Bluetooth Music System'],
                'status' => 'available',
                'sort_order' => 5,
            ],
            [
                'service_type' => 'taxi',
                'name' => 'Force Tempo Traveller AC (12-Seater)',
                'category' => 'Tempo Traveller (12+1)',
                'description' => 'Heavy-duty 12-seater pushback minibus for corporate retreats, student batches, and pilgrimage groups heading to Murudeshwar & Gokarna.',
                'price_base' => 25.00,
                'price_unit' => 'per_km',
                'capacity' => '12+1 Passengers',
                'image_url' => 'https://images.unsplash.com/photo-1464219789935-c2d9d9aba644?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Large Groups',
                'features' => ['Chilled Dual AC', 'Luggage Carrier on Roof', 'Experienced Hill & Ghat Driver', 'Fastag Enabled'],
                'status' => 'available',
                'sort_order' => 6,
            ],
            [
                'service_type' => 'taxi',
                'name' => 'Tata Nexon EV Max Long Range',
                'category' => 'Luxury EV',
                'description' => 'Zero-emission coastal sightseeing in high comfort. Whisper-quiet electric motor, ventilated front seats, and air purifier cabin.',
                'price_base' => 16.00,
                'price_unit' => 'per_km',
                'capacity' => '4+1 Passengers',
                'image_url' => 'https://images.unsplash.com/photo-1550355291-bbee04a92027?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Zero Emissions',
                'features' => ['Chilled Dual AC', 'Fastag Enabled', 'GPS Monitored', 'Clean & Sanitized Daily'],
                'status' => 'available',
                'sort_order' => 7,
            ],

            // ==========================================
            // 3. Backwater Boating (boating)
            // ==========================================
            [
                'service_type' => 'boating',
                'name' => 'Sharavathi Estuary High-Speed Boat Safari',
                'category' => 'Speedboat Safari',
                'description' => 'Adrenaline-packed 45-minute speedboat ride gliding through river channels to the Arabian Sea estuary mouth with sharp turns and sea spray.',
                'price_base' => 450.00,
                'price_unit' => 'per_person',
                'capacity' => '6 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
                'badge' => 'High Adrenaline',
                'features' => ['Life Jackets for All Guests', 'Certified Lifeguard on Board', 'Safety Briefing Included', 'Surround Music System'],
                'status' => 'available',
                'sort_order' => 1,
            ],
            [
                'service_type' => 'boating',
                'name' => 'Twin-Engine Private Speedboat Charter',
                'category' => 'Speedboat Safari',
                'description' => 'Exclusive chartered speedboat for private families and couple shoots. Custom throttle speed and scenic stops at sandspit dunes.',
                'price_base' => 2400.00,
                'price_unit' => 'per_trip',
                'capacity' => '8 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Private Charter',
                'features' => ['Life Jackets for All Guests', 'Certified Lifeguard on Board', 'Sharavathi Island Halt', 'Free Packaged Drinking Water'],
                'status' => 'available',
                'sort_order' => 2,
            ],
            [
                'service_type' => 'boating',
                'name' => 'Royal Sharavathi Wooden Shikara Cruise',
                'category' => 'Sharavathi Shikara Cruise',
                'description' => 'Traditional handcrafted covered wooden shikara boat gliding gently through serene mangrove canopy channels with comfortable cushioned seating.',
                'price_base' => 1500.00,
                'price_unit' => 'per_trip',
                'capacity' => '6 Guests',
                'image_url' => '/images/services/honnavar-backwater-boating.jpg',
                'badge' => 'Top Rated',
                'features' => ['Life Jackets for All Guests', 'Sharavathi Island Halt', 'Mangrove Bird Watching', 'Safety Briefing Included'],
                'status' => 'available',
                'sort_order' => 3,
            ],
            [
                'service_type' => 'boating',
                'name' => 'Romantic Sunset Shikara with Island Halt',
                'category' => 'Sharavathi Shikara Cruise',
                'description' => 'Golden hour cruise timed for sunset over the Arabian Sea confluence. Includes a 20-minute halt on an uninhabited sand island.',
                'price_base' => 1800.00,
                'price_unit' => 'per_trip',
                'capacity' => '4 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Sunset Special',
                'features' => ['Sharavathi Island Halt', 'Life Jackets for All Guests', 'Surround Music System', 'Free Packaged Drinking Water'],
                'status' => 'available',
                'sort_order' => 4,
            ],
            [
                'service_type' => 'boating',
                'name' => 'Emerald Mangrove Guided Kayaking Expedition',
                'category' => 'Mangrove Kayaking Trail',
                'description' => 'Paddle through narrow emerald mangrove channels where motorized boats cannot enter. Peaceful, eco-friendly birdwatching experience.',
                'price_base' => 600.00,
                'price_unit' => 'per_person',
                'capacity' => '2 Guests per Kayak',
                'image_url' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Eco Adventure',
                'features' => ['Life Jackets for All Guests', 'Certified Lifeguard on Board', 'Safety Briefing Included', 'Mangrove Bird Watching'],
                'status' => 'available',
                'sort_order' => 5,
            ],
            [
                'service_type' => 'boating',
                'name' => 'Twilight Estuary Sunset Cruise Yacht',
                'category' => 'Sunset Cruise Yacht',
                'description' => 'Double-decker leisure catamaran cruise with open viewing deck, sunset photo spots, and acoustic music through the Sharavathi delta.',
                'price_base' => 850.00,
                'price_unit' => 'per_person',
                'capacity' => '25 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Open Deck',
                'features' => ['Surround Music System', 'Free Packaged Drinking Water', 'Life Jackets for All Guests', 'Safety Briefing Included'],
                'status' => 'available',
                'sort_order' => 6,
            ],
            [
                'service_type' => 'boating',
                'name' => 'Karavali Luxury Backwater Houseboat Day Stay',
                'category' => 'Houseboat Day Stay',
                'description' => 'All-day luxury river houseboat cruise with dining salon, sun deck, and fresh authentic Karavali fish curry lunch served on board.',
                'price_base' => 7500.00,
                'price_unit' => 'per_trip',
                'capacity' => '10 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Full Day Luxury',
                'features' => ['Sharavathi Island Halt', 'Surround Music System', 'Free Packaged Drinking Water', 'Life Jackets for All Guests'],
                'status' => 'available',
                'sort_order' => 7,
            ],

            // ==========================================
            // 4. Netrani Scuba Diving (scuba)
            // ==========================================
            [
                'service_type' => 'scuba',
                'name' => 'Netrani Island PADI Discovery Scuba (Beginner)',
                'category' => 'PADI Discovery Scuba',
                'description' => 'No swimming skills required. Includes 1-on-1 PADI dive master guide, boat transfer from Murudeshwar, 30-min underwater dive, and HD 4K GoPro video.',
                'price_base' => 2999.00,
                'price_unit' => 'per_dive',
                'capacity' => '1 Diver / 1 Master',
                'image_url' => 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Top Adventure',
                'features' => ['Free 4K Underwater Video & Photos', '1-on-1 PADI Certified Instructor', 'Speedboat Transfer to Netrani', 'Full Scuba Gear & Wetsuit', 'Non-Swimmers Fully Welcome'],
                'status' => 'available',
                'sort_order' => 1,
            ],
            [
                'service_type' => 'scuba',
                'name' => 'Introductory Shore & Shallow Reef Dive',
                'category' => 'Introductory Shore Dive',
                'description' => 'Ideal first step for nervous beginners. Conducted in calm shallow bay with certified instructors before venturing to open water.',
                'price_base' => 1999.00,
                'price_unit' => 'per_dive',
                'capacity' => '1 Diver',
                'image_url' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Beginner Friendly',
                'features' => ['1-on-1 PADI Certified Instructor', 'Full Scuba Gear & Wetsuit', 'Non-Swimmers Fully Welcome', 'Free 4K Underwater Video & Photos'],
                'status' => 'available',
                'sort_order' => 2,
            ],
            [
                'service_type' => 'scuba',
                'name' => 'Netrani Island Deep Coral Reef Boat Dive',
                'category' => 'Netrani Island Boat Dive',
                'description' => 'Descend to 12-18 meters among parrotfish, moray eels, and triggerfish around the Grand Central Station reef of Netrani Island.',
                'price_base' => 3800.00,
                'price_unit' => 'per_dive',
                'capacity' => '2 Divers',
                'image_url' => 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Deep Reef Thrill',
                'features' => ['Speedboat Transfer to Netrani', 'Full Scuba Gear & Wetsuit', '1-on-1 PADI Certified Instructor', 'Fresh Fruits & Light Refreshments'],
                'status' => 'available',
                'sort_order' => 3,
            ],
            [
                'service_type' => 'scuba',
                'name' => 'Netrani Twin Tank Certified Diver Trip',
                'category' => 'Netrani Island Boat Dive',
                'description' => 'Exclusively for PADI/SSI Open Water certified divers. Two guided exploratory dives at Netrani Pinnacle and Coral Nursery.',
                'price_base' => 4500.00,
                'price_unit' => 'per_session',
                'capacity' => '4 Divers',
                'image_url' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Certified Divers',
                'features' => ['Speedboat Transfer to Netrani', 'Full Scuba Gear & Wetsuit', 'Fresh Fruits & Light Refreshments', 'Free 4K Underwater Video & Photos'],
                'status' => 'available',
                'sort_order' => 4,
            ],
            [
                'service_type' => 'scuba',
                'name' => 'Guided Netrani Coral Island Snorkeling Safari',
                'category' => 'Snorkeling & Dolphin Safari',
                'description' => 'Float on the turquoise waters of Netrani with mask, snorkel, and buoyancy jacket. Watch sea turtles and colorful reef fish with ease.',
                'price_base' => 1499.00,
                'price_unit' => 'per_person',
                'capacity' => '20 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Family Snorkeling',
                'features' => ['Speedboat Transfer to Netrani', 'Non-Swimmers Fully Welcome', 'Fresh Fruits & Light Refreshments', 'Free 4K Underwater Video & Photos'],
                'status' => 'available',
                'sort_order' => 5,
            ],
            [
                'service_type' => 'scuba',
                'name' => 'Marine Wildlife & Dolphin Spotting Boat Cruise',
                'category' => 'Snorkeling & Dolphin Safari',
                'description' => 'Morning boat voyage across Arabian Sea waters to spot pods of playful humpback dolphins followed by surface snorkeling near the island.',
                'price_base' => 1200.00,
                'price_unit' => 'per_person',
                'capacity' => '15 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Dolphin Spotting',
                'features' => ['Speedboat Transfer to Netrani', 'Non-Swimmers Fully Welcome', 'Fresh Fruits & Light Refreshments', 'Free 4K Underwater Video & Photos'],
                'status' => 'available',
                'sort_order' => 6,
            ],

            // ==========================================
            // 5. Coastal Homestays (homestay)
            // ==========================================
            [
                'service_type' => 'homestay',
                'name' => 'Sharavathi Riverfront Heritage Teakwood Cottage',
                'category' => 'River Heritage Cottage',
                'description' => 'Traditional Konkan-style heritage villa facing the river with private veranda, hammocks, fresh seafood home dining, and private boat dock.',
                'price_base' => 2200.00,
                'price_unit' => 'per_night',
                'capacity' => '3 Guests / Room',
                'image_url' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Riverfront Serenity',
                'features' => ['Direct Beach / Water Access', 'Free High-Speed Wi-Fi', 'Authentic Karavali Homemade Meals', 'Air Conditioned Rooms', '24/7 Hot Water & Power Backup'],
                'status' => 'available',
                'sort_order' => 1,
            ],
            [
                'service_type' => 'homestay',
                'name' => 'Kasarkod Beachfront Coconut Grove Villa',
                'category' => 'Beachfront Luxury Villa',
                'description' => 'Private luxury villa set directly inside a breezy coconut plantation, 90 seconds walk to Kasarkod Eco Beach with outdoor dining gazebo.',
                'price_base' => 4800.00,
                'price_unit' => 'per_night',
                'capacity' => '6 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Exclusive Beachfront',
                'features' => ['Direct Beach / Water Access', 'Free High-Speed Wi-Fi', 'Air Conditioned Rooms', 'Private Verandah & Garden', 'Campfire & BBQ Facility', 'Secure Car Parking'],
                'status' => 'available',
                'sort_order' => 2,
            ],
            [
                'service_type' => 'homestay',
                'name' => 'Apsarakonda Hilltop Forest Eco-Cottage',
                'category' => 'Forest Eco-Stay',
                'description' => 'Overlooking the Arabian Sea from forested cliffs. Wake up to hornbill calls, sea breeze, and walking trail down to Apsarakonda waterfalls.',
                'price_base' => 2500.00,
                'price_unit' => 'per_night',
                'capacity' => '4 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Nature Retreat',
                'features' => ['Free High-Speed Wi-Fi', 'Authentic Karavali Homemade Meals', '24/7 Hot Water & Power Backup', 'Private Verandah & Garden', 'Secure Car Parking'],
                'status' => 'available',
                'sort_order' => 3,
            ],
            [
                'service_type' => 'homestay',
                'name' => 'Karavali Deluxe AC Family River Suite',
                'category' => 'Deluxe AC Family Suite',
                'description' => 'Two interconnected master bedrooms with modern ensuite bathrooms, large living lounge, and private balcony overlooking Sharavathi island.',
                'price_base' => 3200.00,
                'price_unit' => 'per_night',
                'capacity' => '5 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Family Suite',
                'features' => ['Air Conditioned Rooms', 'Free High-Speed Wi-Fi', 'Authentic Karavali Homemade Meals', '24/7 Hot Water & Power Backup', 'Secure Car Parking'],
                'status' => 'available',
                'sort_order' => 4,
            ],
            [
                'service_type' => 'homestay',
                'name' => 'Emerald Mangrove Cozy Backwater Room',
                'category' => 'Cozy Backwater Room',
                'description' => 'Peaceful double bedroom with balcony hanging over gentle mangrove stream. Ideal for solo writers, backpackers, and couples.',
                'price_base' => 1600.00,
                'price_unit' => 'per_night',
                'capacity' => '2 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Budget Serene',
                'features' => ['Direct Beach / Water Access', 'Free High-Speed Wi-Fi', '24/7 Hot Water & Power Backup', 'Secure Car Parking'],
                'status' => 'available',
                'sort_order' => 5,
            ],
            [
                'service_type' => 'homestay',
                'name' => 'Sunset View Beachside Wooden Cabana',
                'category' => 'Beachfront Luxury Villa',
                'description' => 'Rustic wooden chalet right on the sand with glass front doors opening to the sunset horizon. Fall asleep to the roar of the surf.',
                'price_base' => 3500.00,
                'price_unit' => 'per_night',
                'capacity' => '2 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Beachfront Cabana',
                'features' => ['Direct Beach / Water Access', 'Air Conditioned Rooms', 'Free High-Speed Wi-Fi', 'Campfire & BBQ Facility'],
                'status' => 'available',
                'sort_order' => 6,
            ],
            [
                'service_type' => 'homestay',
                'name' => 'Traditional Malnad Style Courtyard Homestay',
                'category' => 'River Heritage Cottage',
                'description' => '100-year-old restored tiled ancestral house featuring a central open rainwater courtyard (Thotti Mane) and authentic woodfire home cooking.',
                'price_base' => 2800.00,
                'price_unit' => 'per_night',
                'capacity' => '4 Guests',
                'image_url' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Heritage Courtyard',
                'features' => ['Authentic Karavali Homemade Meals', 'Free High-Speed Wi-Fi', 'Private Verandah & Garden', 'Secure Car Parking'],
                'status' => 'available',
                'sort_order' => 7,
            ],

            // ==========================================
            // 6. Local Travel Guide (guide)
            // ==========================================
            [
                'service_type' => 'guide',
                'name' => 'Honnavar Hidden Waterfalls & Mangrove Trail Guide',
                'category' => 'Sharavathi Wildlife Trail',
                'description' => 'Accompanied by a native certified guide to explore secret Apsarakonda streams, hidden forest pools, mangrove walkways, and scenic hilltop lookouts.',
                'price_base' => 900.00,
                'price_unit' => 'per_trip',
                'capacity' => 'Up to 6 People',
                'image_url' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Insider Access',
                'features' => ['Govt Approved Certified Guide', 'Fluent in English, Kannada, Hindi', 'Customized Route According to Group Pace', 'First Aid Trained'],
                'status' => 'available',
                'sort_order' => 1,
            ],
            [
                'service_type' => 'guide',
                'name' => 'Mirjan Fort & Coastal Dynasty Historian',
                'category' => 'Heritage & Temple Specialist',
                'description' => 'Uncover the fascinating 16th century history of Queen Chennabhairadevi (The Pepper Queen), Mirjan Fort battlements, secret escape tunnels, and coastal spice ports.',
                'price_base' => 1200.00,
                'price_unit' => 'per_trip',
                'capacity' => 'Up to 10 People',
                'image_url' => 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Heritage Specialist',
                'features' => ['Govt Approved Certified Guide', 'Deep Historical & Cultural Knowledge', 'Fluent in English, Kannada, Hindi', 'Local Culinary & Shopping Tips'],
                'status' => 'available',
                'sort_order' => 2,
            ],
            [
                'service_type' => 'guide',
                'name' => 'Gokarna 5-Beach Cliff Trek Certified Guide',
                'category' => 'Coastal & Beach Trek Guide',
                'description' => 'Traverse the iconic coastal path from Kudle Beach over headlands to Om Beach, Half Moon Beach, and Paradise Beach with safe cliffside navigation.',
                'price_base' => 1500.00,
                'price_unit' => 'per_day',
                'capacity' => 'Up to 8 People',
                'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Beach Trekking',
                'features' => ['Govt Approved Certified Guide', 'First Aid Trained', 'Customized Route According to Group Pace', 'Fluent in English, Kannada, Hindi'],
                'status' => 'available',
                'sort_order' => 3,
            ],
            [
                'service_type' => 'guide',
                'name' => 'Western Ghats Monsoon Forest & Stream Tracker',
                'category' => 'Sharavathi Wildlife Trail',
                'description' => 'Explore the rain-drenched Western Ghats valleys around Gerusoppa, tracking exotic butterflies, canopy birds, and untamed stream pools safely.',
                'price_base' => 1400.00,
                'price_unit' => 'per_day',
                'capacity' => 'Up to 6 People',
                'image_url' => 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Forest Naturalist',
                'features' => ['Deep Historical & Cultural Knowledge', 'First Aid Trained', 'Govt Approved Certified Guide', 'Customized Route According to Group Pace'],
                'status' => 'available',
                'sort_order' => 4,
            ],
            [
                'service_type' => 'guide',
                'name' => 'Golden Hour Photography & Secret Viewpoints Specialist',
                'category' => 'Photography & Secret Spots Guide',
                'description' => 'Led by an award-winning coastal landscape photographer to hidden cliff lookouts, estuary sandbanks, and fishing harbors at dawn and sunset.',
                'price_base' => 1000.00,
                'price_unit' => 'per_trip',
                'capacity' => 'Up to 4 People',
                'image_url' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Photo Expedition',
                'features' => ['Fluent in English, Kannada, Hindi', 'Customized Route According to Group Pace', 'Local Culinary & Shopping Tips'],
                'status' => 'available',
                'sort_order' => 5,
            ],
            [
                'service_type' => 'guide',
                'name' => 'Murudeshwar Temple Architecture & Mythology Walk',
                'category' => 'Heritage & Temple Specialist',
                'description' => 'Deep dive into the Ravana Atma-Linga legend, the 20-storied Raja Gopura iconography, and the world’s second tallest Lord Shiva statue.',
                'price_base' => 800.00,
                'price_unit' => 'per_trip',
                'capacity' => 'Up to 12 People',
                'image_url' => 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Mythology & Temple',
                'features' => ['Govt Approved Certified Guide', 'Deep Historical & Cultural Knowledge', 'Fluent in English, Kannada, Hindi'],
                'status' => 'available',
                'sort_order' => 6,
            ],

            // ==========================================
            // 7. Karnataka Tour Packages (tours)
            // ==========================================
            [
                'service_type' => 'tours',
                'name' => 'Honnavar Estuary & Murudeshwar Divine Day Tour',
                'category' => '1-Day Honnavar & Murudeshwar',
                'description' => 'Morning Sharavathi backwater boat cruise, visit to Apsarakonda waterfall & Eco Beach, followed by private AC cab transfer to Murudeshwar Shiva Temple.',
                'price_base' => 1850.00,
                'price_unit' => 'per_person',
                'capacity' => 'Min 2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Day Circuit',
                'features' => ['Dedicated Private AC Cab Included', 'All Tolls, Parking & Driver Bata Paid', 'All Sightseeing Entry Tickets Included', 'Dedicated 24/7 Trip Coordinator', 'Zero Hidden Fees Guaranteed'],
                'status' => 'available',
                'sort_order' => 1,
            ],
            [
                'service_type' => 'tours',
                'name' => '2D/1N Coastal Waterfalls & Jog Falls Grand Circuit',
                'category' => '2-Day Coastal & Jog Falls Circuit',
                'description' => 'Comprehensive 2-day vacation covering Honnavar backwaters, Kasarkod Eco Beach, Mirjan Fort, and India’s majestic Jog Falls canyon with overnight stay.',
                'price_base' => 4999.00,
                'price_unit' => 'per_person',
                'capacity' => 'Min 2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Most Popular',
                'features' => ['Dedicated Private AC Cab Included', 'All Sightseeing Entry Tickets Included', 'Complimentary South Indian Breakfast', 'Dedicated 24/7 Trip Coordinator', 'Zero Hidden Fees Guaranteed'],
                'status' => 'available',
                'sort_order' => 2,
            ],
            [
                'service_type' => 'tours',
                'name' => '3D/2N Complete Karavali Heritage, Wildlife & Beach Expedition',
                'category' => '3-Day Karavali Heritage & Nature',
                'description' => 'Covers Honnavar, Gokarna (Om Beach & Mahabaleshwar Temple), Murudeshwar, Yana giant karst rock monoliths, and Sharavathi riverfront homestay.',
                'price_base' => 8499.00,
                'price_unit' => 'per_person',
                'capacity' => 'Min 2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Flagship Holiday',
                'features' => ['Dedicated Private AC Cab Included', 'All Tolls, Parking & Driver Bata Paid', 'All Sightseeing Entry Tickets Included', 'Complimentary South Indian Breakfast', 'Dedicated 24/7 Trip Coordinator'],
                'status' => 'available',
                'sort_order' => 3,
            ],
            [
                'service_type' => 'tours',
                'name' => 'Gokarna Cliffside Beach Hop & Temple Spiritual Trail',
                'category' => 'Gokarna Beach & Temple Trail',
                'description' => 'Full-day excursion from Honnavar to Gokarna: visit ancient Mahabaleshwar Temple, Kudle Beach shacks, Om Beach water sports, and Mirjan Fort on return.',
                'price_base' => 2200.00,
                'price_unit' => 'per_person',
                'capacity' => 'Min 2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Gokarna Day Trip',
                'features' => ['Dedicated Private AC Cab Included', 'All Tolls, Parking & Driver Bata Paid', 'Dedicated 24/7 Trip Coordinator', 'Zero Hidden Fees Guaranteed'],
                'status' => 'available',
                'sort_order' => 4,
            ],
            [
                'service_type' => 'tours',
                'name' => 'Coastal Honeymoon Romantic Getaway Package',
                'category' => '2-Day Coastal & Jog Falls Circuit',
                'description' => 'Special couple package with beachfront candle-lit dining, private sunset shikara cruise, AC cab chauffeur, and floral decorated luxury river cottage.',
                'price_base' => 11999.00,
                'price_unit' => 'per_couple',
                'capacity' => '2 Persons (Couple)',
                'image_url' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Honeymoon Special',
                'features' => ['Dedicated Private AC Cab Included', 'Complimentary South Indian Breakfast', 'Dedicated 24/7 Trip Coordinator', 'Zero Hidden Fees Guaranteed'],
                'status' => 'available',
                'sort_order' => 5,
            ],
            [
                'service_type' => 'tours',
                'name' => 'Netrani Scuba Diving & Coastal Adventure Weekend',
                'category' => '2-Day Coastal & Jog Falls Circuit',
                'description' => 'Ultimate thrills: Day 1 Netrani Island PADI discovery scuba dive with 4K video; Day 2 Sharavathi mangrove speedboat safari and Eco Beach sunset.',
                'price_base' => 6750.00,
                'price_unit' => 'per_person',
                'capacity' => 'Min 2 Persons',
                'image_url' => 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800&auto=format&fit=crop&q=80',
                'badge' => 'Adventure Weekend',
                'features' => ['Dedicated Private AC Cab Included', 'All Sightseeing Entry Tickets Included', 'Dedicated 24/7 Trip Coordinator', 'Zero Hidden Fees Guaranteed'],
                'status' => 'available',
                'sort_order' => 6,
            ],
        ];

        foreach ($items as $item) {
            $serviceItem = ServiceItem::updateOrCreate(
                [
                    'service_type' => $item['service_type'],
                    'name' => $item['name'],
                ],
                $item
            );

            // Ensure primary gallery image exists
            if (! empty($item['image_url'])) {
                ServiceItemImage::firstOrCreate(
                    [
                        'service_item_id' => $serviceItem->id,
                        'image_path' => $item['image_url'],
                    ],
                    [
                        'is_primary' => true,
                        'sort_order' => 0,
                    ]
                );
            }
        }
    }
}
